"""Create a one-click launcher for a trained generation.

    python scripts/make_engine_launcher.py --generation 500 \
        --out "C:\\Users\\Dominik\\Desktop\\projekty.25.08\\chess-app\\engines"

    python scripts/make_engine_launcher.py --all --out <engines dir>

A GUI's engine registry usually stores only a path, with no room for command
line arguments, so each generation gets its own ``.cmd`` that hard-codes
``--weights``. Register that file as the engine; register several of them to
play generation against generation.

The launcher pins the Python interpreter that is running this script, so it
keeps working when the GUI starts it outside your conda environment.
"""

import argparse
import glob
import os
import re
import sys

import _bootstrap  # noqa: F401

TEMPLATE = """@echo off
rem mylc0 -- generation {generation}
rem Generated by scripts/make_engine_launcher.py; safe to move or rename.
setlocal
set "MYLC0_PYTHON={python}"
"%MYLC0_PYTHON%" "{entry}" --weights "{weights}" %*
"""


def generation_of(path: str):
    match = re.search(r"gen_(\d+)", os.path.basename(path))
    return int(match.group(1)) if match else None


def write_launcher(network: str, out_dir: str, project_root: str,
                   python_exe: str, name: str = None) -> str:
    generation = generation_of(network)
    label = name or (f"mylc0-gen{generation:06d}" if generation is not None
                     else "mylc0-" + os.path.splitext(
                         os.path.basename(network))[0])
    entry = os.path.join(project_root, "engine", "mylc0.py")
    path = os.path.join(out_dir, label + ".cmd")
    os.makedirs(out_dir, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(TEMPLATE.format(
            generation=generation if generation is not None else "?",
            python=python_exe, entry=entry,
            weights=os.path.abspath(network)))
    return path


def main() -> int:
    project_root = _bootstrap.PROJECT_ROOT
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--networks", default=os.path.join(project_root,
                                                           "networks"))
    parser.add_argument("--generation", type=int, action="append",
                        help="generation number; repeat for several")
    parser.add_argument("--all", action="store_true",
                        help="one launcher per exported generation")
    parser.add_argument("--latest", action="store_true")
    parser.add_argument("--out", required=True,
                        help="the GUI's engines directory")
    parser.add_argument("--python", default=sys.executable,
                        help="interpreter to pin (default: this one)")
    parser.add_argument("--name", default=None,
                        help="override the launcher file name")
    args = parser.parse_args()

    targets = []
    if args.all:
        targets = sorted(glob.glob(os.path.join(args.networks,
                                                "gen_*.mylc0")))
    if args.generation:
        for gen in args.generation:
            path = os.path.join(args.networks, f"gen_{gen:06d}.mylc0")
            if not os.path.isfile(path):
                print(f"missing: {path}")
                return 1
            targets.append(path)
    if args.latest or not targets:
        latest = os.path.join(args.networks, "latest.mylc0")
        if os.path.isfile(latest):
            targets.append(latest)

    if not targets:
        print(f"no networks found in {args.networks}")
        return 1

    for network in targets:
        name = args.name if len(targets) == 1 else None
        path = write_launcher(network, args.out, project_root, args.python,
                              name)
        print(f"{path}\n    -> {os.path.abspath(network)}")
    print(f"\nRegister the .cmd file(s) above in your GUI. The engine reports "
          f"its generation in the UCI name, so several of them stay "
          f"distinguishable.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
